import "./globals.css";
import type { Metadata } from "next";
import { jetbrainsMono, openSans, cooper, rubik } from "@/lib/fonts";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${openSans.variable}  ${cooper.variable} ${rubik.variable} flex min-h-screen flex-col bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
