# Generated by Django 4.2.5 on 2023-09-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="summary",
            field=models.CharField(max_length=320),
        ),
    ]
