# Generated by Django 4.2.5 on 2023-09-28 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_record_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="citation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="summary",
            field=models.CharField(max_length=256),
        ),
    ]
