# Generated by Django 4.2.5 on 2023-09-29 18:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_alter_record_options_platform_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="details",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
