# Generated by Django 4.2.5 on 2023-11-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_squashed_0006_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="tracker.category",
            ),
        ),
    ]
