# Generated by Django 4.2.5 on 2024-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="record_set", to="tracker.category"
            ),
        ),
    ]
