# Generated by Django 4.2.5 on 2024-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_record_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="category",
        ),
        migrations.AlterField(
            model_name="record",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="records", to="tracker.category"
            ),
        ),
    ]
